import { defineCollection, z } from 'astro:content';

const seoFields = {
  seoTitle: z.string().optional(),
  metaDescription: z.string().optional(),
  h1: z.string().optional(),
  keywords: z.array(z.string()).default([]),
  canonical: z.string().optional(),
  ogImage: z.string().optional(),
  noindex: z.boolean().default(false),
};

const specItem = z.object({
  label: z.string(),
  value: z.string(),
  group: z.string().optional(),
});

const homepage = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    seoTitle: z.string().optional(),
    metaDescription: z.string().optional(),
    h1: z.string(),
    keywords: z.array(z.string()).default([]),
    canonical: z.string().optional(),
    ogImage: z.string().optional(),
    noindex: z.boolean().default(false),
    hero: z.object({
      eyebrow: z.string(),
      title: z.string(),
      description: z.string(),
      image: z.string().default('/placeholders/battery-system.svg'),
      imageAlt: z.string().optional(),
      primaryCtaLabel: z.string().default('Explore Products'),
      primaryCtaHref: z.string().default('/products'),
      secondaryCtaLabel: z.string().default('View System Packages'),
      secondaryCtaHref: z.string().default('/solutions'),
      tertiaryCtaLabel: z.string().default('Request Quote'),
      tertiaryCtaHref: z.string().default('/contact'),
      floatingEyebrow: z.string().optional(),
      floatingTitle: z.string().optional(),
      floatingDescription: z.string().optional(),
    }),
    stats: z.array(z.object({ label: z.string(), value: z.string() })).default([]),
    why: z.object({
      visible: z.boolean().default(true),
      eyebrow: z.string().default('Why Callsun'),
      title: z.string(),
      description: z.string().optional(),
      cards: z.array(z.object({ title: z.string(), description: z.string() })).default([]),
    }),
    productsSection: z.object({ visible: z.boolean().default(true), eyebrow: z.string(), title: z.string(), description: z.string().optional() }),
    solutionsSection: z.object({ visible: z.boolean().default(true), eyebrow: z.string(), title: z.string(), description: z.string().optional(), linkLabel: z.string().optional(), linkHref: z.string().optional() }),
    casesSection: z.object({ visible: z.boolean().default(true), eyebrow: z.string(), title: z.string(), description: z.string().optional(), linkLabel: z.string().optional(), linkHref: z.string().optional() }),
    marketingSection: z.object({
      visible: z.boolean().default(true),
      eyebrow: z.string(),
      title: z.string(),
      description: z.string().optional(),
      checklist: z.array(z.string()).default([]),
    }),
    resourcesSection: z.object({ visible: z.boolean().default(true), eyebrow: z.string(), title: z.string(), linkLabel: z.string().optional(), linkHref: z.string().optional() }),
  }),
});

const products = defineCollection({
  type: 'data',
  schema: z.object({
    name: z.string(),
    slug: z.string(),
    category: z.enum(['standard-module', 'custom-module']),
    model: z.string().optional(),
    tagline: z.string(),
    tech: z.string(),
    certifications: z.array(z.string()).default([]),
    benefits: z.array(z.string()).default([]),
    warranty: z.string().optional(),
    relatedSolutions: z.array(z.string()).default([]),
    relatedCases: z.array(z.string()).default([]),
    image: z.string().default('/placeholders/solar-panel.svg'),
    imageAlt: z.string().optional(),
    description: z.string(),
    specs: z.array(specItem).default([]),
    applications: z.array(z.string()).default([]),
    downloads: z.array(z.object({ label: z.string(), url: z.string() })).default([]),
    order: z.number().default(0),
    featured: z.boolean().default(false),
    ...seoFields,
  }),
});

const solutions = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    type: z.enum(['grid-tied', 'off-grid']),
    capacityLabel: z.string(),
    pvCapacity: z.string().optional(),
    batteryCapacity: z.string().optional(),
    image: z.string().default('/placeholders/battery-system.svg'),
    imageAlt: z.string().optional(),
    summary: z.string(),
    components: z.array(z.object({ category: z.string(), name: z.string(), quantity: z.string().optional(), note: z.string().optional() })).default([]),
    topologySteps: z.array(z.object({ label: z.string(), description: z.string().optional() })).default([]),
    benefits: z.array(z.string()).default([]),
    downloads: z.array(z.object({ label: z.string(), url: z.string() })).default([]),
    relatedCases: z.array(z.string()).default([]),
    useCases: z.array(z.string()).default([]),
    relatedProducts: z.array(z.string()).default([]),
    order: z.number().default(0),
    featured: z.boolean().default(false),
    ...seoFields,
  }),
});

const applications = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    summary: z.string(),
    image: z.string().default('/placeholders/case-rooftop.svg'),
    recommendedSolutions: z.array(z.string()).default([]),
    relatedProducts: z.array(z.string()).default([]),
    order: z.number().default(0),
    ...seoFields,
  }),
});

const news = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    publishDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    author: z.string().default('Callsun'),
    cover: z.string().optional(),
    category: z.enum(['Press', 'Product', 'Industry', 'Technical', 'Sustainability']),
    tags: z.array(z.string()).default([]),
    relatedPosts: z.array(z.string()).default([]),
    relatedProducts: z.array(z.string()).default([]),
    relatedSolutions: z.array(z.string()).default([]),
    relatedCases: z.array(z.string()).default([]),
    ctaTitle: z.string().optional(),
    ctaDescription: z.string().optional(),
    ctaLabel: z.string().optional(),
    ctaHref: z.string().optional(),
    featured: z.boolean().default(false),
    draft: z.boolean().default(false),
    ...seoFields,
  }),
});

const downloads = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    description: z.string().optional(),
    fileUrl: z.string(),
    fileType: z.enum(['PDF', 'ZIP', 'DOC', 'XLS', 'Image', 'External']).default('PDF'),
    fileSize: z.string().optional(),
    category: z.enum(['Datasheet', 'Manual', 'Certificate', 'Guide', 'Catalog', 'Warranty', 'Installation']),
    relatedProduct: z.string().optional(),
    relatedProducts: z.array(z.string()).default([]),
    relatedSolutions: z.array(z.string()).default([]),
    tags: z.array(z.string()).default([]),
    version: z.string().optional(),
    updatedAt: z.coerce.date().optional(),
    requiresLeadCapture: z.boolean().default(false),
    featured: z.boolean().default(false),
    order: z.number().default(0),
    ...seoFields,
  }),
});

const cases = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    client: z.string().optional(),
    location: z.string(),
    region: z.enum(['Domestic', 'Overseas']).default('Domestic'),
    industry: z.string().optional(),
    capacityKW: z.number().optional(),
    capacityMWh: z.number().optional(),
    segment: z.enum(['Small C&I', 'Mid-Scale C&I', 'Large C&I', 'Solar + Storage']).default('Mid-Scale C&I'),
    completedAt: z.coerce.date().optional(),
    application: z.enum(['Commercial & Industrial', 'Residential', 'Municipal', 'Solar + Storage']),
    coverImage: z.string().default('/placeholders/case-rooftop.svg'),
    gallery: z.array(z.string()).default([]),
    description: z.string(),
    projectBackground: z.string().optional(),
    customerPainPoints: z.array(z.string()).default([]),
    solutionOverview: z.string().optional(),
    businessResults: z.array(z.string()).default([]),
    projectParameters: z.array(z.object({ label: z.string(), value: z.string() })).default([]),
    salesAngle: z.string().optional(),
    casePdf: z.string().optional(),
    relatedProducts: z.array(z.string()).default([]),
    relatedSolutions: z.array(z.string()).default([]),
    featured: z.boolean().default(false),
    order: z.number().default(0),
    ...seoFields,
  }),
});

const supportPages = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    summary: z.string(),
    body: z.string(),
    order: z.number().default(0),
    ...seoFields,
  }),
});

const navigation = defineCollection({
  type: 'data',
  schema: z.object({
    label: z.string(),
    href: z.string(),
    description: z.string().optional(),
    image: z.string().optional(),
    order: z.number().default(0),
    visible: z.boolean().default(true),
    footerVisible: z.boolean().default(true),
    children: z.array(z.object({
      label: z.string(),
      href: z.string(),
      description: z.string().optional(),
      image: z.string().optional(),
      order: z.number().default(0),
      visible: z.boolean().default(true),
    })).default([]),
  }),
});

const customPages = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    urlPath: z.string(),
    pageType: z.enum(['SEO Page', 'Company Page', 'Support Page', 'Legal Page', 'Campaign Page']).default('SEO Page'),
    category: z.string().optional(),
    eyebrow: z.string().optional(),
    summary: z.string(),
    coverImage: z.string().optional(),
    imageAlt: z.string().optional(),
    ctaLabel: z.string().default('Request a Quote'),
    ctaHref: z.string().default('/contact'),
    secondaryCtaLabel: z.string().optional(),
    secondaryCtaHref: z.string().optional(),
    sections: z.array(z.object({
      eyebrow: z.string().optional(),
      heading: z.string(),
      description: z.string().optional(),
      items: z.array(z.object({ title: z.string(), description: z.string() })).default([]),
    })).default([]),
    faqs: z.array(z.object({ question: z.string(), answer: z.string() })).default([]),
    relatedLinks: z.array(z.object({ label: z.string(), href: z.string(), description: z.string().optional() })).default([]),
    order: z.number().default(0),
    draft: z.boolean().default(false),
    ...seoFields,
  }),
});

const landingPages = defineCollection({
  type: 'data',
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    audience: z.string(),
    campaign: z.string().optional(),
    adGroup: z.string().optional(),
    targetKeywords: z.array(z.string()).default([]),
    hero: z.object({
      eyebrow: z.string().optional(),
      title: z.string(),
      description: z.string(),
      image: z.string().optional(),
      imageAlt: z.string().optional(),
      primaryCtaLabel: z.string().default('Request a Quote'),
      primaryCtaHref: z.string().default('#landing-form'),
      secondaryCtaLabel: z.string().optional(),
      secondaryCtaHref: z.string().optional(),
    }),
    trustBadges: z.array(z.string()).default([]),
    painPoints: z.array(z.object({ title: z.string(), description: z.string() })).default([]),
    valueProps: z.array(z.object({ title: z.string(), description: z.string() })).default([]),
    offerCards: z.array(z.object({ title: z.string(), description: z.string(), linkLabel: z.string().optional(), linkHref: z.string().optional() })).default([]),
    recommendedProducts: z.array(z.string()).default([]),
    recommendedSolutions: z.array(z.string()).default([]),
    relatedCases: z.array(z.string()).default([]),
    downloads: z.array(z.object({ label: z.string(), url: z.string() })).default([]),
    formTitle: z.string().default('Request campaign pricing'),
    formDescription: z.string().optional(),
    thankYouMessage: z.string().default('Inquiry endpoint is reserved for the next CRM phase.'),
    ctaLabel: z.string().default('Request a Quote'),
    draft: z.boolean().default(true),
    ...seoFields,
  }),
});

export const collections = { homepage, products, solutions, applications, news, downloads, cases, supportPages, navigation, customPages, landingPages };
